server:
  port: 8007
spring:
  application:
    name: cloud-learn-gateway
  cloud:
    gateway:
      discovery:
        locator:
         enabled: true # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。

         
         
         
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug